### ISSUE TITLE
Upgrade project to NetStandard 2.0

### ISSUE THREAD

**Issue by azuken** [thomasgalliker/HighlightMarker#3]
Hi, 

Is there any chance that this project can be upgraded to NetStandard ?

Thank you in advance for your response.

**Comment by thomasgalliker** [comment]
Ah sure. I just didnt use it recently. I might also remove Windows Phone support by this chance.

**Comment by thomasgalliker** [comment]
Finally, there is a new preview version of HighlightMarker and HighlightMarker.Forms available:
[https://www.nuget.org/packages/HighlightMarker/3.0.6-pre](https://www.nuget.org/packages/HighlightMarker/3.0.6-pre)
