### ISSUE TITLE
.Net MAUI?

### ISSUE THREAD

**Issue by LennoxP90** [thomasgalliker/HighlightMarker#7]
Will there be a MAUI release?

**Comment by thomasgalliker** [comment]
Good point. I gonna have to look into that any time soon.

**Comment by thomasgalliker** [comment]
The .NET MAUI nuget package will be published under following name: HighlightMarker.MAUI and you'll find it here https://www.nuget.org/packages/HighlightMarker.MAUI/

Please, @LennoxP90 , can you try the first pre-release nuget package and let me know if everything works fine.

**Comment by LennoxP90** [comment]
Sorry for the late response, this seems to work fine for my application.
